default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: turbonote
  password: NhKv8B6tn5fsl0ZbLmKtrLbr4FCLH9qU
  host: dpg-d0qf22mmcj7s73e01ilg-a.oregon-postgres.render.com
  port: 5432
  database: turbonote

development:
  <<: *default

test:
  <<: *default
  database: notebook_test  # tu peux créer une base test séparée

production:
  <<: *default